import type { Locator } from '@playwright/test';
import { Ui5Bridge, type Ui5Target } from './Ui5Bridge';
import { Ui5GridTable } from './Ui5GridTable';
import { Ui5Locator } from './Ui5Locator';
import { idsSelector } from './domSelectors';
import { waitForUi5 } from './waits';

/** Row control types tried, in order, when looking for a `sap.m.Table`/`sap.m.List`-based result
 * list inside a value help dialog - the same list `Ui5Table` itself tries, since a value help
 * dialog's result list is exactly that: a `sap.m.Table`/`sap.m.List`, just found by scoped search
 * instead of a locator you already have. */
const M_ROW_TYPES = [
  'sap.m.ColumnListItem',
  'sap.m.ObjectListItem',
  'sap.m.StandardListItem',
  'sap.m.CustomListItem',
];

/**
 * A helper for value help ("F4 help") dialogs - the picker that opens when you click the little
 * icon at the end of a value-help-enabled `sap.m.Input` (including one generated by a
 * `sap.ui.comp.smartfield.SmartField`). See docs/value-help-dialog.md.
 *
 * Two things make this genuinely awkward to automate without a dedicated helper:
 *
 * - **The trigger isn't documented anywhere obvious.** SAPUI5 renders the value-help icon as a
 *   child element of the input with an id ending in `-vhi` - a stable, verified convention (this
 *   framework checked it against both a plain `sap.m.Input` sample and a `SmartField`-generated
 *   one), but not something you'd find by reading the input control's own public API.
 * - **The dialog that opens, and its result list's implementation, both vary.** A simple app might
 *   open a plain `sap.m.Dialog`-based `sap.m.SelectDialog` with a `sap.m.Table` inside; a Fiori
 *   Elements/SmartField app commonly opens a `sap.ui.comp.valuehelpdialog.ValueHelpDialog` (itself
 *   a `sap.m.Dialog` subclass) with a `sap.ui.table.Table` (a *virtualized* grid table - see
 *   [`Ui5GridTable`](Ui5GridTable.ts)) inside instead. `selectRow()` below checks for both, so you
 *   don't have to know or care which one a given app happens to use.
 */
export class Ui5ValueHelpDialog {
  private constructor(
    private readonly target: Ui5Target,
    private readonly containerId: string,
  ) {}

  /**
   * Clicks the value-help trigger icon for the field `fieldLocator` resolves to, then waits for
   * the resulting dialog/popover to open and wraps it - the same "trigger separately, then wait"
   * split [`Ui5Dialog.open()`](Ui5Dialog.ts) uses, just with the specific trigger this control
   * needs built in, since - unlike a plain toolbar button - it isn't something you'd otherwise
   * know how to find.
   *
   * `fieldLocator` should resolve to the input (or `SmartField`) itself, e.g.
   * `ui5(page).id('idDeliveryTransport')` or `ui5(page).controlType('sap.m.Input')` - not the
   * icon. Throws a clear error if the resolved field has no value-help icon at all.
   */
  static async openFor(
    fieldLocator: Ui5Locator,
    options: { timeout?: number } = {},
  ): Promise<Ui5ValueHelpDialog> {
    const timeout = options.timeout ?? 10000;
    const resolved = await fieldLocator.resolve({ timeout });
    const target = resolved.page();
    // Scoped to the field's own DOM subtree (`[id$="-vhi"]` = "ends with -vhi") rather than a
    // page-wide search, and scoped *within* the resolved element rather than assuming the icon's
    // id is `<fieldId>-vhi` outright - verified to hold for both a directly-authored `sap.m.Input`
    // (the icon is a direct child of the input's own root) and a `SmartField`-generated one (the
    // icon is nested one level deeper, inside the `SmartField`'s own rendered `sap.m.Input`).
    const trigger = resolved.first().locator('[id$="-vhi"]');
    if ((await trigger.count()) === 0) {
      throw new Error(
        `[playwright-sapui5] Ui5ValueHelpDialog.openFor: the resolved field has no value-help icon (no descendant element with an id ending in "-vhi"). Is this field's value help actually enabled?`,
      );
    }
    await trigger.first().click({ timeout });

    const deadline = Date.now() + timeout;
    for (;;) {
      const popups = await Ui5Bridge.findOpenPopups(target);
      if (popups.length > 0) {
        // A dialog reporting `isOpen() === true` only means it exists and has started opening -
        // its own contents (notably a `sap.ui.table.Table` result list's internal row pool, which
        // this framework verified is built slightly *after* the dialog itself becomes "open," as
        // part of the dialog's own opening animation) can still be settling for a moment longer.
        // `waitForUi5` here (best-effort - a slow-to-settle dialog shouldn't fail `openFor()`
        // outright) is what makes `selectRow()` reliable immediately afterward, instead of racing
        // that settling the same way calling `Ui5GridTable.from()` too early can - see
        // docs/ui5-grid-table.md#a-timing-gotcha-worth-knowing for the same underlying issue.
        await waitForUi5(target, { timeout: Math.max(0, deadline - Date.now()) }).catch(() => {});
        return new Ui5ValueHelpDialog(target, popups[0].id);
      }
      if (Date.now() >= deadline) {
        throw new Error(
          `[playwright-sapui5] Ui5ValueHelpDialog.openFor: clicked the value-help icon, but no dialog/popover opened within ${timeout}ms.`,
        );
      }
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }

  /** This dialog's own `title` property - see [`Ui5Dialog.title()`](Ui5Dialog.ts) for the same
   * caveat about dialogs that build their header out of a separate control instead. */
  async title(): Promise<string> {
    const result = await Ui5Bridge.getControlProperty(this.target, this.containerId, 'title');
    return typeof result.value === 'string' ? result.value : '';
  }

  /**
   * Finds the first result row containing `text` - checking a `sap.m.Table`/`sap.m.List`-based
   * result list first (a plain `sap.m.SelectDialog`, or a `ValueHelpDialog` configured to use
   * one), then falling back to a `sap.ui.table.Table`-based one (`ValueHelpDialog`'s more common
   * default) - and clicks it. In the single-select configuration this framework verified against
   * two real, live apps, clicking a row both selects *and confirms* it, closing the dialog with
   * that value applied - no separate "OK" click needed. If the dialog you're testing is configured
   * for multi-select instead (checkboxes, an explicit confirm button), use `.button(...)`/
   * `.clickButton(...)` below after selecting rows yourself, the same way you would with
   * `Ui5Dialog`.
   */
  async selectRow(text: string, options: Parameters<Locator['click']>[0] = {}): Promise<void> {
    for (const type of M_ROW_TYPES) {
      const rows = await Ui5Bridge.findDescendantControlsByType(
        this.target,
        this.containerId,
        type,
      );
      if (rows.length === 0) continue;
      const candidates = this.target.locator(idsSelector(rows.map((r) => r.id)));
      const match = candidates.filter({ hasText: text }).first();
      if ((await match.count()) > 0) {
        await match.click(options);
        return;
      }
    }

    const gridTables = await Ui5Bridge.findDescendantControlsByType(
      this.target,
      this.containerId,
      'sap.ui.table.Table',
    );
    if (gridTables.length > 0) {
      const gridTable = await Ui5GridTable.from(
        Ui5Locator.id(this.target, gridTables[0].id, { exact: true }),
      );
      const row = await gridTable.rowContaining(text);
      if ((await row.count()) > 0) {
        await row.click(options);
        return;
      }
    }

    throw new Error(
      `[playwright-sapui5] Ui5ValueHelpDialog.selectRow: no row containing "${text}" found (checked both a sap.m.Table/List result list and a sap.ui.table.Table, if present). If the row you want isn't currently rendered in a scrollable grid table, resolve it yourself via Ui5GridTable.scrollToRow() first.`,
    );
  }

  /** The button inside this dialog whose visible text matches `text` - same scoped-search
   * behavior as [`Ui5Dialog.button()`](Ui5Dialog.ts). Use this for "Cancel", or for an explicit
   * "OK"/"Select" confirm button in a multi-select configuration. */
  async button(text: string): Promise<Locator> {
    const buttons = await Ui5Bridge.findDescendantControlsByType(
      this.target,
      this.containerId,
      'sap.m.Button',
    );
    const candidates = this.target.locator(idsSelector(buttons.map((b) => b.id)));
    return candidates.filter({ hasText: text }).first();
  }

  /** Convenience: `.button(text)` then `.click()` on it, in one call. */
  async clickButton(text: string, options: Parameters<Locator['click']>[0] = {}): Promise<void> {
    const button = await this.button(text);
    await button.click(options);
  }

  /** Convenience: clicks the "Cancel" button, closing the dialog without applying a selection. */
  async cancel(options: Parameters<Locator['click']>[0] = {}): Promise<void> {
    await this.clickButton('Cancel', options);
  }

  /** Waits until this dialog is no longer open - same behavior as
   * [`Ui5Dialog.waitForClose()`](Ui5Dialog.ts). Call this after `.selectRow()` in a multi-select
   * configuration (where selecting a row doesn't close the dialog on its own) or after
   * `.clickButton(...)`/`.cancel()`, before your test moves on. */
  async waitForClose(options: { timeout?: number } = {}): Promise<void> {
    const timeout = options.timeout ?? 5000;
    const deadline = Date.now() + timeout;
    for (;;) {
      const popups = await Ui5Bridge.findOpenPopups(this.target);
      if (!popups.some((p) => p.id === this.containerId)) return;
      if (Date.now() >= deadline) {
        throw new Error(
          `[playwright-sapui5] Ui5ValueHelpDialog did not close within ${timeout}ms.`,
        );
      }
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }
}
