import type { Ui5ControlDump } from '../core/types';

// Pure layout/container controls are excluded from generated output - they're rarely useful
// as named locators in a Page Object and would otherwise dominate the generated file.
const CONTAINER_TYPES = new Set([
  'sap.m.Page',
  'sap.m.App',
  'sap.m.SplitApp',
  'sap.m.SplitContainer',
  'sap.m.NavContainer',
  'sap.m.Panel',
  'sap.m.Toolbar',
  'sap.m.Bar',
  'sap.m.VBox',
  'sap.m.HBox',
  'sap.m.FlexBox',
  'sap.m.ScrollContainer',
  'sap.f.DynamicPage',
  'sap.f.DynamicPageTitle',
  'sap.f.DynamicPageHeader',
  'sap.ui.layout.VerticalLayout',
  'sap.ui.layout.HorizontalLayout',
  'sap.ui.layout.Grid',
  'sap.ui.layout.form.Form',
  'sap.ui.layout.form.SimpleForm',
  'sap.ui.core.mvc.XMLView',
  'sap.ui.core.mvc.View',
  'sap.ui.core.ComponentContainer',
]);

function isInterestingControlType(type: string): boolean {
  return !CONTAINER_TYPES.has(type);
}

function toCamelCase(raw: string): string {
  const cleaned = raw
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
    .map((word, i) =>
      i === 0
        ? word.charAt(0).toLowerCase() + word.slice(1)
        : word.charAt(0).toUpperCase() + word.slice(1),
    )
    .join('');
  if (!cleaned) return 'control';
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

function sanitizeForComment(text: string): string {
  const collapsed = text.replace(/[\r\n\t]+/g, ' ').trim();
  return collapsed.length > 60 ? `${collapsed.slice(0, 57)}...` : collapsed;
}

function shortId(id: string): string {
  return id.includes('--') ? id.split('--').pop()! : id;
}

/**
 * Turns a control tree dump (from `Ui5Bridge.dumpControlTree`) into the source of a
 * `Ui5Page` subclass. The output is a starting point, not a finished file - review names
 * before committing, since they're derived mechanically from control ids/types.
 */
export function generatePageObjectSource(dump: Ui5ControlDump[], className: string): string {
  const seen = new Set<string>();
  const members = dump
    .filter((c) => isInterestingControlType(c.type))
    .map((c) => {
      const idPart = shortId(c.id);
      const base = toCamelCase(idPart) || toCamelCase(c.type.split('.').pop() ?? 'control');
      let name = base;
      let n = 1;
      while (seen.has(name)) {
        n += 1;
        name = `${base}${n}`;
      }
      seen.add(name);
      return { name, idPart, type: c.type, properties: c.properties };
    });

  const lines: string[] = [];
  lines.push(`import type { Page } from '@playwright/test';`);
  lines.push(`import { Ui5Page } from 'playwright-sapui5';`);
  lines.push('');
  lines.push(`/**`);
  lines.push(` * Auto-generated by \`pw-sapui5 generate\`. Review before committing:`);
  lines.push(` * member names are derived from control ids and may not be meaningful.`);
  lines.push(` */`);
  lines.push(`export class ${className} extends Ui5Page {`);
  lines.push(`  constructor(page: Page) {`);
  lines.push(`    super(page);`);
  lines.push(`  }`);
  lines.push('');
  for (const m of members) {
    const hint = Object.entries(m.properties)
      .map(([k, v]) => `${k}="${sanitizeForComment(v)}"`)
      .join(' ');
    lines.push(`  // ${m.type}${hint ? ` ${hint}` : ''}`);
    lines.push(`  get ${m.name}() {`);
    lines.push(`    return this.id(${JSON.stringify(m.idPart)});`);
    lines.push(`  }`);
    lines.push('');
  }
  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}
